---
title: "___"
author: "___, ___, ___, ___"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
bibliography: bibliography/references.bib
---

```{r setup, include=FALSE}
# Ceci est nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))

# Configuration de l'environnement SciViews::R
SciViews::R(___, lang = "fr")
```

# Introduction et but

(voir [résumé biblio](doubs_biblio.html)).

# Matériel et méthodes

(voir [rapport](doubs_report.html))

# Analyses

<!--% Dans ce carnet de notes, vous devez expérimenter les différentes méthodes d'analyse multivariées vues dans le cours. Conservez la structure proposée et répartissez-vous le travail de manière équitable en fonction des consignes. -->

## Description des données

<!--% Cette partie doit permettre de comprendre les différents jeux de données que vous traitez. Vous devez présenter et résumer (de manière numérique dans des tableaux de synthèse et/ou graphique) les tables, et les variables à disposition. Préciser également s'il y a des valeurs manquantes, ainsi que le type de données (quantitatives continues ou discrètes, qualitatives ordonnées ou non = variables "facteurs)". Si c'est pertinent, vérifiez la relation entre les variables et transformez-les si nécessaire. -->

<!--# Au niveau de la répartition du travail, chaque étudiant doit contribuer à un ou deux graphiques ou tableaux de synthèse. -->

## Regroupement

<!--% Choisissez deux analyses cah les plus pertinentes (deux étudiants). Chacun interprétera en 3 à 5 phrases juste en dessous du dendrogramme l'analyse qu'il a réalisée. -->

### CAH 1

```{r cah1}

```

<!--% Interprétez la cah1 ci-dessous. -->

### CAH 2

```{r cah2}

```

<!--% Interprétez la cah2 ci-dessous. -->

### Choix CAH

<!--% Retenez le regroupement qui vous paraît le meilleur et ajoutez-le comme variable supplémentaire `group` dans votre jeu de données. -->

```{r groups}

```

## Ordination

<!--% Effectuez deux analyses (deux étudiants différents) soit ACP, soit AFC selon ce qui est le plus pertinent. Dans les représentations, indiquer en couleur l'un des regroupements que vous avez retenue (meilleure CAH). -->

### Ordination 1

```{r acp_afc1}
___
summary(___)
```

```{r acp_afc1_screeplot}

```

<!--% Interprétez le résumé de votre analyse et le graphique des éboulis en 3 à 5 phrases ci-dessous. -->

```{r acp_afc1_plot1}

```

<!--% Interprétez le graphique acp_afc1_plot1 en 3 à 5 phrases. -->

```{r acp_afc1_plot2}

```

<!--% Interprétez le graphique acp_afc1_plot2 en 3 à 5 phrases. -->

<!--% Ajoutez d'autres graphiques si nécessaire et interprétez-les ci-dessous. -->

### Ordination 2

```{r acp_afc2}
___
summary(___)
```

```{r acp_afc2_screeplot}

```

<!--% Interprétez le résumé de votre analyse et le graphique des éboulis en 3 à 5 phrases ci-dessous. -->

```{r acp_afc2_plot1}

```

<!--% Interprétez le graphique acp_afc2_plot1 en 3 à 5 phrases. -->

```{r acp_afc2_plot2}

```

<!--% Interprétez le graphique acp_afc2_plot2 en 3 à 5 phrases. -->

<!--% Ajoutez d'autres graphiques si nécessaire et interprétez-les ci-dessous. -->

<!--# Vous devez arriver jusqu'ici à la fin du module 7. -->

## Analyse multitableaux

<!--% Partie II (module 8) : Effectuez une analyse globale multitableaux (AFM) sur vos données. Réalisez au moins deux graphiques les plus pertinents et interprétez-les (travail à répartir entre 2 et 3 étudiants qui ont moins contribué à la partie I). -->

```{r afm}

```

```{r afm_plot1}

```

<!--% Interprétez le graphique afm_plot2 en 3 à 5 phrases. -->

```{r afm_plot2}

```

<!--% Interprétez le graphique afm_plot2 en 3 à 5 phrases. -->

<!--% Ajoutez d'autres graphiques si nécessaire et interprétez-les ci-dessous. -->

# Discussion et conclusions

<!--% Listez les éléments principaux que vous retenez de votre analyse, sous forme de liste à points concise. -->
